CREATE TABLE IF NOT EXISTS `pages_seo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page_key` varchar(64) NOT NULL,
  `page_name` varchar(100) NOT NULL,
  `page_url` varchar(255) NOT NULL,
  `meta_title` varchar(255) NOT NULL DEFAULT '',
  `meta_description` text DEFAULT NULL,
  `meta_keywords` text DEFAULT NULL,
  `h1_heading` varchar(255) NOT NULL DEFAULT '',
  `content` longtext DEFAULT NULL,
  `canonical_url` varchar(255) DEFAULT '',
  `og_title` varchar(255) DEFAULT '',
  `og_description` text DEFAULT NULL,
  `og_image` varchar(255) DEFAULT '',
  `schema_json` longtext DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_page_key` (`page_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `pages_seo` (`page_key`, `page_name`, `page_url`, `meta_title`, `meta_description`, `meta_keywords`, `h1_heading`, `content`, `canonical_url`) VALUES
('home', 'Home Page', '/', 
 'AI Education Company India – AI Courses & Certification – SSD Prayas',
 'SSD Prayas — India\'s AI education company. Online AI courses, certification & beginner programmes for students, educators & professionals.',
 'ai education company, best ai learning platform india, ai for education, ai education india, ai certification, online ai classes for students, ai course for beginners india, ssd prayas, nep 2020 ai education, ai skilling india',
 'AI Education for a Future-Ready Bharat',
 'Practical, hands-on AI education for school students, teachers and working professionals across India.',
 'https://ssdprayas.com/'),

('ai-for-school', 'AI for School', '/ai-for-school',
 'AI for Schools in India – AI Training – SSD Prayas',
 'SSD Prayas delivers AI education for schools across India — training educators, teaching AI in schools with a NEP 2020 curriculum and certification.',
 'ai for schools in india, ai training for schools, ai education for schools, teaching ai in schools, ai teaching school, nep 2020 ai curriculum, ai for school programme, school ai certification',
 'AI for Schools in India',
 'We don\'t hand over a syllabus and walk away. Our AI training for schools model puts your own teachers through certified training, runs classes inside the computer lab you already have, and leaves your campus capable of teaching AI on its own — long after our team has moved to the next school.',
 'https://ssdprayas.com/ai-for-school'),

('programmes', 'Programmes', '/programmes',
 'AI Programmes for Students, Educators & Professionals | SSD Prayas',
 'Grade-wise AI curriculum for Class 3–12, L1/L2 educator training, and applied AI upskilling for working professionals — online or offline.',
 'ai programmes, ai curriculum school, teacher ai training, nep 2020 ai courses, professional ai skilling',
 'The SSD Prayas Learning Journey',
 'AI is not one course taught once. Our curriculum grows with the learner — from a Class 3 child meeting a computer, to a Class 12 student building real AI projects, to a teacher who can carry the whole programme forward.',
 'https://ssdprayas.com/programmes'),

('government', 'Government Projects', '/government',
 'Government AI Skilling Projects Across India | SSD Prayas',
 'State-scale AI skilling for government departments — partner onboarding, L1/L2 educator batches, student enrolment and certification tracking.',
 'government ai skilling, state scale ai education, institutional ai training india, government school ai project',
 'Large-Scale AI Skilling, Across Multiple States',
 'SSD Prayas delivers government and institutional AI skilling at state scale — managing partner onboarding, educator training batches, student enrolment and certification tracking through a single monitored system.',
 'https://ssdprayas.com/government'),

('about', 'About Us', '/about',
 'About SSD Prayas – Our AI Education Mission',
 'SSD Prayas brings practical AI education to students, educators and professionals across India — online, offline and at government scale.',
 'about ssd prayas, ai education mission, future ready bharat, practical ai skills',
 'Building India\'s AI-Ready Generation',
 'SSD Prayas exists for one reason — to make sure practical AI skills reach every classroom, every teacher and every working professional, not just the ones in metro cities.',
 'https://ssdprayas.com/about'),

('careers', 'Careers', '/careers',
 'Careers at SSD Prayas – Hiring AI Educators',
 'Join SSD Prayas as an AI Educator. Hybrid roles across Indian states, training students and teachers in practical AI. Apply with your resume.',
 'ai educator jobs, ai teaching careers india, trainer jobs ai, edtech educator hiring',
 'Teach the Skill That Changes Careers',
 'SSD Prayas hires educators only. If you can hold a classroom and you are willing to learn AI properly, we will train you, certify you and put you in front of students who need you.',
 'https://ssdprayas.com/careers'),

('contact', 'Contact Us', '/contact',
 'Contact SSD Prayas – Start Your AI Journey',
 'Talk to SSD Prayas about bringing AI education to your school or organisation. Call, WhatsApp or send an enquiry — we respond within 24 hours.',
 'contact ssd prayas, book ai demo, school ai partnership, ai training inquiry',
 'Let\'s Plan Your AI Roll-out',
 'Whether you want to introduce AI across a school network, certify your teachers or discuss a government-scale rollout — talk to our team.',
 'https://ssdprayas.com/contact'),

('blogs', 'Blogs Listing', '/blogs',
 'SSD Prayas Blog – AI Education Insights & Stories',
 'Stories and insights on AI education, NEP 2020 and educator training — what\'s really working inside Indian classrooms.',
 'ai education blog, nep 2020 ai articles, classroom ai insights, ai for school stories',
 'The SSD Prayas Blog',
 'Stories, ideas and insights on AI education, NEP 2020, educator training and what\'s really working inside Indian classrooms.',
 'https://ssdprayas.com/blogs')
ON DUPLICATE KEY UPDATE 
  `page_name`=VALUES(`page_name`),
  `page_url`=VALUES(`page_url`);
